// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3E-JJg2DJ_GKFYv8pn4h0AU39PecTL5g',
    appId: '1:274411483319:web:8eaa6dbc1ac33f80ce1d32',
    messagingSenderId: '274411483319',
    projectId: 'listyapp-29eee',
    authDomain: 'listyapp-29eee.firebaseapp.com',
    storageBucket: 'listyapp-29eee.firebasestorage.app',
    measurementId: 'G-NYX8R2BVDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTCKN8rwEfDxhVx8gfUtvLO1viwkZbx4',
    appId: '1:274411483319:android:8b68b669a7729496ce1d32',
    messagingSenderId: '274411483319',
    projectId: 'listyapp-29eee',
    storageBucket: 'listyapp-29eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMvBJzKUjCkI23BG1J6zHKTbpQJYd8vGE',
    appId: '1:274411483319:ios:7a8a231bf8404d51ce1d32',
    messagingSenderId: '274411483319',
    projectId: 'listyapp-29eee',
    storageBucket: 'listyapp-29eee.firebasestorage.app',
    iosBundleId: 'com.example.listyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMvBJzKUjCkI23BG1J6zHKTbpQJYd8vGE',
    appId: '1:274411483319:ios:7a8a231bf8404d51ce1d32',
    messagingSenderId: '274411483319',
    projectId: 'listyapp-29eee',
    storageBucket: 'listyapp-29eee.firebasestorage.app',
    iosBundleId: 'com.example.listyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3E-JJg2DJ_GKFYv8pn4h0AU39PecTL5g',
    appId: '1:274411483319:web:4124bfb43399e49cce1d32',
    messagingSenderId: '274411483319',
    projectId: 'listyapp-29eee',
    authDomain: 'listyapp-29eee.firebaseapp.com',
    storageBucket: 'listyapp-29eee.firebasestorage.app',
    measurementId: 'G-VMJ8RN0BPS',
  );
}
